# Generated by Django 2.1.7 on 2019-03-31 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionPaper',
        ),
    ]
