# Generated by Django 2.1.7 on 2019-02-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
