# Generated by Django 2.1.7 on 2020-02-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_name', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('authon', models.CharField(max_length=100)),
            ],
        ),
    ]
